---
# tasks file for ansible-role-netmaker-podman

- name: "Create netmaker pod"
  containers.podman.podman_pod:
    name: "netmaker-pod"
    state: "created"
    infra_name: "netmaker-infra"
    recreate: no
    ports:
    - "{{ netmaker_server_port }}:8443"
    - "{{ netmaker_mqtt_port }}:8883"
    - "{{ netmaker_dashboard_port }}:8080"
    - "{{ netmaker_wireguard_port_range }}:51821-51830/udp"
